# Setup
title: Jaembong blog
description: Hi!
url: https://jaembong.github.io
avatar: /assets/img/avatar.jpg
paginate: 5
permalink: pretty
# cover_image: /assets/img/bg_1.jpg
cover_bg_color: "black"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: vszhub
#   card: summary
# logo: logo.png
social:
  name: jaembong
  links:
    - https://github.com/jaembong
google_site_verification: google5cc40506a21a5a7f.html
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: jaembong
  url: https://github.com/jaembong/
  email: jaembong@gmail.com
